### ISSUE TITLE
Needs a pkg-config file

### ISSUE THREAD

**Issue by mbacarella** [PortMidi/portmidi#1]
So that the build/link arguments can be probed via pkg-config.

Perhaps this is up to distro maintainers to provide but maybe we can discuss here.

**Comment by rbdannenberg** [comment]
The latest version seems to be in good shape now. I'm sure there will be a couple of tweaks, and then I should give it another round of testing, but it was tested on Mac, Win, & Linux without problems before cleaning up the repo and adding some documentation.
