### ISSUE TITLE
The cmake file should be installed in CMAKE_INSTALL_LIBDIR

### ISSUE THREAD

**Issue by cryptomilk** [PortMidi/portmidi#10]
https://github.com/PortMidi/portmidi/blob/587043f211b03205e3e2b9ef5dbd9efd19324f81/CMakeLists.txt#L125

The cmake files should be installed in ${CMAKE_INSTALL_LIBDIR} to take /usr/lib64 into account!

**Comment by rbdannenberg** [comment]
Are you saying the line should be set(PORTMIDI_INSTALL_CMAKEDIR ${CMAKE_INSTALL_LIBDIR}) ?
If so, would it be even better to remove the set command and just replace occurrences of PORTMIDI_INSTALL_CMAKEDIR with CMAKE_INSTALL_LIBDIR? That would just be in DESTINATION and INSTALL_DESTINATION options (lines 130, 135, 146). Maybe this would even be the default for DESTINATION, in which case could the DESTINATION and/or INSTALL_DESTINATION options be removed?
