### ISSUE TITLE
portmidi 2.0.3 - enabling build of tests makes the build fail

### ISSUE THREAD

**Issue by GvMariani** [PortMidi/portmidi#21]
If you pass -DBUILD_PORTMIDI_TESTS="ON" to cmake, then the build fails because it does not find the pmlist.c source file.
Commenting out the add_test(pmlist) line in pm_tests/CMakeLists.txt file fixes the issue.

**Comment by rbdannenberg** [comment]
Darn. I forgot to add that file. I just pushed it to the repo. I think I'll refrain from another release unless it seems necessary.
