### ISSUE TITLE
Apple M2 support?

### ISSUE THREAD

**Issue by Engil** [PortMidi/portmidi#39]
Hello!

I've been trying to use portmidi on my M2 MacBook Air, but it seems that I'm encountering a few issues. (I cannot connect to any devices, as of current development tree.)

I would be willing to investigate, but I would like first, if you have time, to enquire about the current status of the M1 support (with some fixes included as of May 23rd), and possible pointers as to what may be going wrong so I don't start totally in the dark.

From what I see of the M1 fixes, it seems it had to do with how time was handled?

Thank you for your time, and for this great library. :-)

**Comment by Engil** [comment]
Ha, I did not run the test programs, I will come back to you in a few days, thank you for your reply!

**Comment by rbdannenberg** [comment]
I still haven't gotten around to a methodical test (needed now on all 4 platforms counting intel and M2 as separate), but haven't heard any complaints, so I'm closing this.
