### ISSUE TITLE
Improve pkg-config file generation

### ISSUE THREAD

**Issue by kmilos** [PortMidi/portmidi#43]
It would be good to improve the CMake generated .pc file for relocatability - namely, it should use [${prefix} etc. variables and relative paths whenever possible](https://people.freedesktop.org/~dbn/pkg-config-guide.html), but still support absolute paths when so required.

See e.g. [libjxl](https://github.com/libjxl/libjxl/blob/3f6ec60ce6890132c1e2ea9719de5981042a1d96/lib/jxl.cmake#L642-L663) and [libtiff](https://gitlab.com/libtiff/libtiff/-/blob/31d9e9f73dc8b6fa599c931d9ff058d8ea32795c/cmake/PkgConfig.cmake#L48-63)

**Comment by rbdannenberg** [comment]
My recommendation is to build portmidi from sources and link to it statically. A .pc file, whatever that is, is not necessary. However, I recognized that there are many development styles and preferences, and I'm open to supporting them by including contributions to CMake files, even when I can't test them, have no specs, cannot recreate every environment these are meant for, or anticipate actual needs. Feel free to contribute changes, or maybe someone else will respond to this. I'll leave the issue up for awhile, but will probably "close as not planned" at some point in the future if there's no other action. Thanks for pointing out the issue.
