### ISSUE TITLE
README: reference to PortMidi/portsmf is broken/missing

### ISSUE THREAD

**Issue by luzpaz** [PortMidi/portmidi#61]
In the https://github.com/PortMidi/portmidi#portsmf paragraph the link is 404 
since https://github.com/PortMidi/portsmf doesn't exist.

**Comment by rbdannenberg** [comment]
Thanks - low priority, but I'll get to it. If you are interested in portsmf, it *does* exist, but separated from this repo.

**Comment by Zopolis4** [comment]
Where is the canonical repository for portsmf? 

Searching for it yields a few repositories, and it looks like the canonical one is https://github.com/rbdannenberg/portsmf, but I'd like to be sure.

**Comment by rbdannenberg** [comment]
That's correct: rbdannenberg/portsmf. I created portsmf while working on Audacity, which is still open source and still reads/writes MIDI, so there are also portsmf sources in the Audacity source tree (also on github). It's quite possible that there are some bug fixes in Audacity's version that have not made it to rbdannenberg/portsmf.
