### ISSUE TITLE
midithru example doesn't seem to work

### ISSUE THREAD

**Issue by mikerodd** [PortMidi/portmidi#77]
Hello there :)
I'm trying to use the examples provided, I can't make midithru.c working : the program is supposed to send an echo 2 secs after the event, when I start it, a bunch of events are sent but after that, there is no echo.
I use vmpk connected and fluidsynth connected to midi through, on Ubuntu 22.04, libportmidi-dev:amd64 1:217-6 

the program seems to capture and send the data but there is no note.

any idea ? 
![Capture d’écran du 2024-10-31 15-18-36](https://github.com/user-attachments/assets/cbdee26f-f900-491d-9221-e68e2de1c757)

**Comment by rbdannenberg** [comment]
The "bunch of events" and "fluidsynth warning: Ringbuffer full" suggests something strange is going on outside of PortMidi. Maybe there is some kind of loopback into/through vmpk. I would suggest send vmpk to mm.c (midi monitor) to see what you get. Then use testiio.c to test sending notes to fluidsynth (still observing vmpk and mm). Maybe that will give some insight.

**Comment by mikerodd** [comment]
I cloned your repository rather than using the library and example files provided by the Ubuntu package, and it's working now :)
the package seems to point to the sourceforge repository (even the latest 24.04, probably an older version
